### PR TITLE
Closer to what i thought week5 was

### PR DESCRIPTION
**Pull request by EasyAsABC123**

### CODE REVIEW

**Comment by arhill05** [comment]
Do we put that stuff together for them, or do they do that as we step through the readme? Other weeks just start where the previous week left off I thought.

**Comment by EasyAsABC123** [comment]
they do start where the previous week left off, week4 is broken right now...i pushed like half week5 and half week3...who knows what happened...need to grab week 3 then follow the directions there to make week4

**Comment by arhill05** [comment]
I'd say we merge this one then and revisit it once we fix week4.

**Review by arhill05 — APPROVED** [review]

**Comment by EasyAsABC123** [comment]
👍

**Pull request merged**
